proxmox_api_host: "XXXXXXXXXXXXX"
proxmox_api_port: "XXXXXXXXXXXXX"
proxmox_api_user: "XXXXXXXXXXXXX"
proxmox_api_token_id: "XXXXXXXXXXXXX"
proxmox_api_token_secret: "XXXXXXXXXXXXX"
proxmox_node: "XXXXXXXXXXXXX"
proxmox_ssh_user: "ansible"
proxmox_ssh_port: "22"
proxmox_ssh_identity_file: "../../files/home.priv"
proxmox_timeout: "300"
proxmox_template_name: "XXXXXXXXXXXXX"
proxmox_ciuser: "root"